# workaround to enable reload4j when using commons-logging-1.3.0
# see https://logging.apache.org/blog/2023/12/02/apache-common-logging-1.3.0.html
org.apache.commons.logging.Log = org.apache.commons.logging.impl.Log4JLogger
