
#
# stdout appends to console
#
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{ISO8601} %5p [%t] %c - %m%n


#
# set log levels
#
log4j.rootLogger=INFO, stdout

# debug in serva
log4j.logger.ch.serva=info

# ignore verbose startup config from config package
log4j.logger.org.hibernate.cfg=info

# log JDBC activity, e.g. SQL statement batching
log4j.logger.org.hibernate.jdbc=info

# log schema export/update
log4j.logger.org.hibernate.tool.hbm2ddl=debug

