
###############################################################################
# email
#

# address of your serva instance
address            = http://serva.net/example/

# your email address
mail.from          = mail@serva.net

# the username to login to your SMTP server
mail.user          = mail@serva.net

# the password to login to your SMTP server
mail.password      = 123

# your SMTP server
mail.smtp.host     = mail.serva.net

###############################################################################
# paths
#

# path to domain config directory
path.domainconfigdir = "/root/domainconfig/"

